name: 发布到 NPM

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: '发布标签 (latest/beta)'
        required: true
        default: 'latest'
        type: choice
        options:
          - latest
          - beta

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: 安装依赖
        run: npm ci
        
      - name: 运行代码检查
        run: npm run lint
          
      - name: 构建项目
        run: npm run build
        
      - name: 发布到 NPM (latest)
        if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.tag == 'latest')
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: 发布到 NPM (beta)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag == 'beta'
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}